Fix using of PosixPath instead of string
Traceback (most recent call last):
  File "./convert.py", line 95, in <module>
    shutil.copy2( presentation , 'prezentace.zip')
  File "/usr/lib/python3.5/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/usr/lib/python3.5/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/usr/lib/python3.5/genericpath.py", line 90, in samefile
    s1 = os.stat(f1)
TypeError: argument should be string, bytes or integer, not PosixPath